<?php

namespace App\Helpers;

use App\Models\Setting;
use Illuminate\Support\Facades\File;
use Intervention\Image\Laravel\Facades\Image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Services\TwilioService;
use Twilio\Rest\Client;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Crypt;
use Hashids;
use Carbon\Carbon;
class Settings
{

    public static function getSetting($setting_key)
    {
        $settingData = Setting::Select('setting_value')->where("setting_key", $setting_key)->first();
        return $settingData->setting_value;
    }

    public static function downloadpdf($pdf)
    {
        // Set paper
        $pdf->setPaper('a4', 'portrait');

        // Get user
        $userName = auth()->check() ? auth()->user()->name : 'System';

        // Get DomPDF instance
        $domPdf = $pdf->getDomPDF();

        // Render
        $domPdf->render();

        $canvas = $domPdf->getCanvas();

        // Page width
        $width = $canvas->get_width();

        // ✅ TOP POSITION (very important)
        $y = 15;

        // ✅ Left (Generated By)
        $canvas->page_text(
            40,
            $y,
            "Generated By: " . $userName,
            null,
            9,
            [0, 0, 0]
        );

        // ✅ Right (Page Number)
        $canvas->page_text(
            $width - 150,
            $y,
            "Page {PAGE_NUM} of {PAGE_COUNT}",
            null,
            9,
            [0, 0, 0]
        );

        return $pdf;
    }


    public static function downloadLandscapePdf($pdf)
    {
        // Set paper
        $pdf->setPaper('a4', 'landscape');

        // Get logged-in user
        $userName = auth()->check() ? auth()->user()->name : 'System';

        // Render first
        $pdf->render();

        $domPdf = $pdf->getDomPdf();
        $canvas = $domPdf->get_canvas();

        // Page dimensions
        $width = $canvas->get_width();

        // ✅ Top-right (Page Number)
        $canvas->page_text(
            $width - 150,
            15,
            "Page {PAGE_NUM} of {PAGE_COUNT}",
            null,
            9,
            [0, 0, 0]
        );

        // ✅ Top-left (Generated By)
        $canvas->page_text(
            20,
            15,
            "Generated By: " . $userName,
            null,
            9,
            [0, 0, 0]
        );

        return $pdf;
    }

    public static function updateBreadcrumbRoute($breadcrumb, $routes, $values)
    {
        foreach ($routes as $i => $key) {
            $breadcrumb[$key] = $values[$i] ?? $breadcrumb[$key];
        }

        return $breadcrumb;
    }

    public static function roleRedirect($page, $message = null, $type = 'success')
    {
        $prefix = '';
        if (Auth::check()) {
            if (Auth::user()->user_type_id == config('constants.superadmin')) {
                $prefix = 'administrator.';
            } elseif (Auth::user()->user_type_id == config('constants.admin')) {
                $prefix = 'admin.';
            }
        }

        $route = $prefix . $page;


        return $message
            ? redirect()->route($route)->with($type, $message)
            : redirect()->route($route);
    }

    public static function getUserRole()
    {
        $user = Auth::user();

        return match ($user->user_type_id) {
            config('constants.superadmin') => 'administrator',
            config('constants.admin') => 'admin',
            default => 'admin',
        };
    }


    public static function getPunchIn($attendanceData, $staffId, $monthdate, $csvornot = 1)
    {
        $punchInDate = '';
        $br = '<br>';
        if ($csvornot == 0) {
            $br = "\n";
        }
        foreach ($attendanceData as $atttendanceRecord) {
            if (($atttendanceRecord->staff_id == $staffId) && (date('Y-m-d', strtotime($atttendanceRecord->punch_in_date)) == date('Y-m-d', strtotime($monthdate)))) {
                $punchInDate = 'Punch-In ' . $br . '(' . date(\Config::get('constants.dateformat.dmy'), strtotime($atttendanceRecord->punch_in_date)) . ')';
            }
        }
        return $punchInDate;
    }

    public static function getPunchOut($attendanceData, $staffId, $monthdate, $csvornot = 1)
    {
        $punchOutDate = '';
        $br = '<br>';
        if ($csvornot == 0) {
            $br = "\n";
        }
        foreach ($attendanceData as $atttendanceRecord) {
            if (($atttendanceRecord->staff_id == $staffId) && (date('Y-m-d', strtotime($atttendanceRecord->punch_out_date)) == date('Y-m-d', strtotime($monthdate)))) {
                $punchOutDate = 'Punch-Out ' . $br . '(' . date(\Config::get('constants.dateformat.dmy'), strtotime($atttendanceRecord->punch_out_date)) . ')';
            }
        }
        return $punchOutDate;
    }
    public static function formatDate($date, $format)
    {
        if (strpos($date, '/') !== false) {
            return date($format, strtotime(str_replace('/', '-', $date)));
        } else {
            return date($format, strtotime($date));
        }

    }

    public static function checkAndformatDate($date, $format)
    {
        if (empty($date))
            return "";

        if (strpos($date, '/') !== false) {
            return date($format, strtotime(str_replace('/', '-', $date)));
        } else {
            return date($format, strtotime($date));
        }

    }

    public static function getEncodeCodeWithHashids($data)
    {
        return (!empty($data)) ? substr(str_shuffle("123456789"), 0, 5) . Hashids::encode($data) : '';
    }
    public static function getEncodeCode($data)
    {
        return (!empty($data)) ? substr(str_shuffle("123456789"), 0, 5) . $data : '';
    }
    public static function getDecodeCodeWithHashids($encodedCode)
    {
        return (!empty($encodedCode)) ? Hashids::decode(substr($encodedCode, 5)) : 0;
    }
    public static function getDecodeCode($encodedCode)
    {
        return (!empty($encodedCode)) ? substr($encodedCode, 5) : '';
    }



    public static function getFormattedDate($date)
    {
        return (!empty($date)) ? date(\Config::get('constants.dateformat.slashdmyonly'), strtotime($date)) : '';
    }
    public static function getFormattedDatetime($date)
    {
        return (!empty($date)) ? date(\Config::get('constants.dateformat.slashdmy'), strtotime($date)) : '';
    }

    public static function getInventoryAdjustment($encodedId)
    {
        $id = self::getDecodeCode($encodedId);

        $map = [
            1 => ['route' => Config::get('constants.typesofinventory.1'), 'adjustment' => 'add'],
            2 => ['route' => Config::get('constants.typesofinventory.2'), 'adjustment' => 'sale'],
            3 => ['route' => Config::get('constants.typesofinventory.3'), 'adjustment' => 'return'],
            4 => ['route' => Config::get('constants.typesofinventory.4'), 'adjustment' => 'damage'],
            5 => ['route' => Config::get('constants.typesofinventory.5'), 'adjustment' => 'deduct'],
        ];

        return $map[$id] ?? ['route' => null, 'adjustment' => null];
    }

    public static function getRouteName($encodedId)
    {
        $id = self::getDecodeCode($encodedId);

        $map = [
            1 => ['route' => Config::get('constants.typesofinventory.1'), 'adjustment' => 'add'],
            2 => ['route' => Config::get('constants.typesofinventory.2'), 'adjustment' => 'sale'],
            3 => ['route' => Config::get('constants.typesofinventory.3'), 'adjustment' => 'return'],
            4 => ['route' => Config::get('constants.typesofinventory.4'), 'adjustment' => 'damage'],
            5 => ['route' => Config::get('constants.typesofinventory.5'), 'adjustment' => 'deduct'],
        ];

        return $map[$id] ?? ['route' => null, 'adjustment' => null];
    }

    public static function isValidEAN13($barcode)
    {
        // Must be exactly 13 digits
        if (!preg_match('/^[0-9]{13}$/', $barcode)) {
            return false;
        }

        $sum = 0;

        for ($i = 0; $i < 12; $i++) {
            $digit = (int) $barcode[$i];
            $sum += ($i % 2 === 0) ? $digit : $digit * 3;
        }

        $checkDigit = (10 - ($sum % 10)) % 10;

        return (int) $barcode[12] === $checkDigit;
    }

    public static function getAdjustmentIdFromRoute($routeName)
    {
        $map = [
            'admin.barcode' => 1,
            'admin.sales-barcode' => 2,
            'admin.return-barcode' => 3,
            'admin.damage-barcode' => 4,
            'admin.deduct-barcode' => 5,
            'admin.no-barcode' => 6,
        ];
        return $map[$routeName] ?? 1; // default = 1
    }


    public static function generateEan13()
    {
        // Generate random 12-digit base
        $base = '';
        for ($i = 0; $i < 12; $i++) {
            $base .= rand(0, 9);
        }

        // Calculate checksum
        $sum = 0;
        for ($i = 0; $i < 12; $i++) {
            $digit = (int) $base[$i];
            $sum += ($i % 2 === 0) ? $digit : $digit * 3;
        }

        $checkDigit = (10 - ($sum % 10)) % 10;

        return $base . $checkDigit;
    }


    public static function uploadimage($request, $fieldname, $pathname, $oldFilename = null)
    {
        $filename = '';

        if ($request->hasFile($fieldname)) {

            $ds = DIRECTORY_SEPARATOR;
            $folderpath = 'uploads' . $ds . $pathname . $ds;

            $imageFile = $request->file($fieldname);
            $filename = time() . '.' . $imageFile->getClientOriginalExtension();

            // Ensure directories exist
            $folders = ['original', 'small', 'medium', 'large'];

            foreach ($folders as $folder) {
                $dir = public_path($folderpath . $folder . $ds);
                if (!File::exists($dir)) {
                    File::makeDirectory($dir, 0755, true);
                }
            }

            // Delete old files
            if ($oldFilename) {
                foreach ($folders as $folder) {
                    $oldPath = public_path($folderpath . $folder . $ds . $oldFilename);
                    if (File::exists($oldPath)) {
                        File::delete($oldPath);
                    }
                }
            }

            /* -------- ORIGINAL IMAGE -------- */
            Image::read($imageFile)
                ->save(public_path($folderpath . 'original' . $ds . $filename));

            /* -------- RESIZED IMAGES -------- */
            $sizes = [
                'small' => [100, 100],
                'medium' => [300, 300],
                'large' => [600, 600],
            ];

            foreach ($sizes as $folder => [$width, $height]) {
                Image::read($imageFile)
                    ->cover($width, $height)
                    ->save(public_path($folderpath . $folder . $ds . $filename));
            }
        }

        return $filename;
    }


    public static function isFileExists($foldername, $imagename)
    {
        $isExist = 0;
        $ds = DIRECTORY_SEPARATOR;
        $folderpath = 'uploads' . $ds . $foldername . $ds . 'original' . $ds;
        $imagePath = $folderpath . $imagename;
        if (file_exists(public_path($imagePath))) {
            $isExist = 1;
        }
        return $isExist;
    }

    public static function getcustomnumberformat($amount)
    {
        return number_format($amount, 2);
        $parts = explode('.', number_format($amount, 2, '.', ''));
        $intPart = $parts[0];

        if (strlen($intPart) > 4) {
            $firstPart = substr($intPart, 0, 2);
            $lastPart = substr($intPart, 2);
            $formatted = $firstPart . ',' . $lastPart;
        } else {
            $formatted = $intPart;
        }

        return $formatted . '.' . $parts[1];
    }

    public static function applyDateRange($query, Request $request, $column = 'date', $defaultdate = false)
    {
        if ($request->has('invoice_no')) {
            $defaultdate = false;
        }

        if ($request->filled('from_date') && $request->filled('to_date')) {
            $fromDate = Settings::formatDate($request->get('from_date'), 'Y-m-d');
            $toDate = Settings::formatDate($request->get('to_date'), 'Y-m-d');
            $query->whereDate($column, '>=', $fromDate)->whereDate($column, '<=', $toDate);
        } elseif ($request->filled('from_date')) {
            $fromDate = Settings::formatDate($request->get('from_date'), 'Y-m-d');
            $query->whereDate($column, '>=', $fromDate);
        } elseif ($request->filled('to_date')) {
            $toDate = Settings::formatDate($request->get('to_date'), 'Y-m-d');
            $query->whereDate($column, '<=', $toDate);
        } elseif ($defaultdate) {
            $query->whereDate($column, '>=', date('Y-m-d'))->whereDate($column, '<=', date('Y-m-d'));
        }
        return $query;
    }



    public static function downloadcsvfile($data, $fileName)
    {
        // ✅ Proper headers
        header('Content-Type: text/csv; charset=UTF-8');
        header("Content-Disposition: attachment; filename=\"$fileName\"");
        header('Pragma: no-cache');
        header('Expires: 0');

        $fp = fopen('php://output', 'w');

        // ✅ IMPORTANT: Add UTF-8 BOM (fixes ₹, ₦, etc in Excel)
        fprintf($fp, chr(0xEF) . chr(0xBB) . chr(0xBF));

        foreach ($data as $row) {
            fputcsv($fp, $row);
        }

        fclose($fp);
        exit;
    }


    public static function sendSms($to, $message)
    {
        try {
            $sid = config('services.twilio.sid');
            $token = config('services.twilio.token');
            $from = config('services.twilio.from');

            $client = new Client($sid, $token);

            $client->messages->create($to, [
                'from' => $from,
                'body' => $message,
            ]);

            Log::info("✅ SMS sent to {$to}: {$message}");
            return ['success' => true, 'message' => 'SMS sent successfully'];
        } catch (\Exception $e) {
            Log::error("❌ Twilio SMS Error: " . $e->getMessage());
            return ['success' => false, 'message' => $e->getMessage()];
        }
    }
    public static function route_exists(string $name): bool
    {
        return Route::has($name);
    }
    public static function isAdmin()
    {
        return auth()->check() && auth()->user()->designation_id == 2;
    }

    public static function userScope($query, $column = 'id')
    {
        if (!self::isAdmin()) {
            $query->where($column, auth()->id());
        }

        return $query;
    }

    public static function userdatetime($datetime, $format = 'h:i A')
    {
        if (!$datetime) {
            return null;
        }

        $timezone = auth()->user()->timezone ?? config('app.timezone');

        return Carbon::parse($datetime)
            ->timezone($timezone)
            ->format($format);
    }


}

//Settings::sendSms('+2348012345678', 'Hello! Your order has been confirmed.');


